/**
 * Readable aliases over the generated OpenAPI types.
 *
 * api.ts is generated by `make openapi` and must not be edited. Its shapes are
 * nested (`components["schemas"]["X"]`), which is unreadable at call sites — so
 * this thin hand-written file names them. It is the only file that reaches into
 * the generated one.
 */
import type { components } from "./api";

export type ReadyStatus = components["schemas"]["ReadyOutputBody"];
export type HealthCheck = components["schemas"]["CheckDTO"];

export type Session = components["schemas"]["SessionResponse"];
export type AuthUser = components["schemas"]["UserView"];

export type Post = components["schemas"]["View"];
export type PostFeed = components["schemas"]["FeedOutputBody"];
export type PostList = components["schemas"]["CardListOutputBody"];
export type CreatePostBody = components["schemas"]["CreateInputBody"];
export type UpdatePostBody = components["schemas"]["UpdateInputBody"];
export type TagChip = components["schemas"]["Chip"];

export type Comment = components["schemas"]["CommentView"];
export type CommentTree = components["schemas"]["CommentTreeOutputBody"];
export type ReactionState = components["schemas"]["ReactionStateOutputBody"];
export type PresignResult = components["schemas"]["PresignOutputBody"];
export type SearchResults = components["schemas"]["SearchOutputBody"];
export type SearchHit = components["schemas"]["SearchHitView"];
