/**
 * Readable aliases over the generated OpenAPI types.
 *
 * api.ts is generated by `make openapi` and must not be edited. Its shapes are
 * nested (`components["schemas"]["X"]`), which is unreadable at call sites — so
 * this thin hand-written file names them. It is the only file that reaches into
 * the generated one.
 */
import type { components } from "./api";

export type ReadyStatus = components["schemas"]["ReadyOutputBody"];
export type HealthCheck = components["schemas"]["CheckDTO"];

export type Session = components["schemas"]["SessionResponse"];
export type AuthUser = components["schemas"]["UserView"];
