// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comment.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCommentTx = `-- name: CreateCommentTx :one
INSERT INTO comments (id, post_id, author_id, parent_id, body_markdown, body_html, depth)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, post_id, author_id, parent_id, body_markdown, body_html, depth, created_at, updated_at, deleted_at
`

type CreateCommentTxParams struct {
	ID           uuid.UUID
	PostID       uuid.UUID
	AuthorID     uuid.UUID
	ParentID     pgtype.UUID
	BodyMarkdown string
	BodyHtml     string
	Depth        int16
}

func (q *Queries) CreateCommentTx(ctx context.Context, arg CreateCommentTxParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createCommentTx,
		arg.ID,
		arg.PostID,
		arg.AuthorID,
		arg.ParentID,
		arg.BodyMarkdown,
		arg.BodyHtml,
		arg.Depth,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.ParentID,
		&i.BodyMarkdown,
		&i.BodyHtml,
		&i.Depth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, post_id, author_id, parent_id, body_markdown, body_html, depth, created_at, updated_at, deleted_at FROM comments WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.ParentID,
		&i.BodyMarkdown,
		&i.BodyHtml,
		&i.Depth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const incrementPostCommentCount = `-- name: IncrementPostCommentCount :exec
UPDATE posts SET comment_count = comment_count + $1 WHERE id = $2
`

type IncrementPostCommentCountParams struct {
	Delta  int32
	PostID uuid.UUID
}

func (q *Queries) IncrementPostCommentCount(ctx context.Context, arg IncrementPostCommentCountParams) error {
	_, err := q.db.Exec(ctx, incrementPostCommentCount, arg.Delta, arg.PostID)
	return err
}

const listCommentsForPost = `-- name: ListCommentsForPost :many
SELECT id, post_id, author_id, parent_id, body_markdown, body_html, depth, created_at, updated_at, deleted_at FROM comments
WHERE post_id = $1
ORDER BY created_at ASC
`

// The whole tree in one query: two levels only, so the service groups replies
// under their parents in Go. Soft-deleted rows are kept so a deleted comment
// with replies still renders as a placeholder.
func (q *Queries) ListCommentsForPost(ctx context.Context, postID uuid.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listCommentsForPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.ParentID,
			&i.BodyMarkdown,
			&i.BodyHtml,
			&i.Depth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCommentTx = `-- name: SoftDeleteCommentTx :one
UPDATE comments SET deleted_at = now()
WHERE id = $1 AND author_id = $2 AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteCommentTxParams struct {
	ID       uuid.UUID
	AuthorID uuid.UUID
}

func (q *Queries) SoftDeleteCommentTx(ctx context.Context, arg SoftDeleteCommentTxParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteCommentTx, arg.ID, arg.AuthorID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateCommentTx = `-- name: UpdateCommentTx :one
UPDATE comments SET body_markdown = $1, body_html = $2, updated_at = now()
WHERE id = $3 AND author_id = $4 AND deleted_at IS NULL
RETURNING id, post_id, author_id, parent_id, body_markdown, body_html, depth, created_at, updated_at, deleted_at
`

type UpdateCommentTxParams struct {
	BodyMarkdown string
	BodyHtml     string
	ID           uuid.UUID
	AuthorID     uuid.UUID
}

func (q *Queries) UpdateCommentTx(ctx context.Context, arg UpdateCommentTxParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateCommentTx,
		arg.BodyMarkdown,
		arg.BodyHtml,
		arg.ID,
		arg.AuthorID,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.ParentID,
		&i.BodyMarkdown,
		&i.BodyHtml,
		&i.Depth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
