// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package sqlcgen

import (
	"context"
)

const pingDatabase = `-- name: PingDatabase :one
SELECT 1::int AS ok
`

// Round-trip thật qua đường sqlc để trang trạng thái chứng minh được cả chặng
// Postgres → repository → service, chứ không chỉ chứng minh pool mở được.
func (q *Queries) PingDatabase(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, pingDatabase)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
