// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package sqlcgen

import (
	"context"
)

const pingDatabase = `-- name: PingDatabase :one
SELECT 1::int AS ok
`

// A real round-trip through the sqlc path, so the status page proves the whole
// Postgres -> repository -> service chain rather than just that the pool opened.
func (q *Queries) PingDatabase(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, pingDatabase)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
