// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Bookmark struct {
	UserID    uuid.UUID
	PostID    uuid.UUID
	CreatedAt time.Time
}

type Comment struct {
	ID           uuid.UUID
	PostID       uuid.UUID
	AuthorID     uuid.UUID
	ParentID     pgtype.UUID
	BodyMarkdown string
	BodyHtml     string
	Depth        int16
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    pgtype.Timestamptz
}

type OauthAccount struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	AccessTokenEnc []byte
	Scopes         []string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Post struct {
	ID             uuid.UUID
	AuthorID       uuid.UUID
	Slug           string
	Title          string
	Subtitle       *string
	BodyMarkdown   string
	BodyHtml       string
	CoverImageUrl  *string
	Status         string
	ReadingMinutes int32
	CanonicalUrl   *string
	CommentCount   int32
	ReactionCount  int32
	ViewCount      int64
	PublishedAt    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      pgtype.Timestamptz
	SearchVector   interface{}
}

type PostTag struct {
	PostID   uuid.UUID
	TagID    uuid.UUID
	Position int16
}

type Reaction struct {
	UserID    uuid.UUID
	PostID    uuid.UUID
	Kind      string
	CreatedAt time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	FamilyID  uuid.UUID
	ExpiresAt time.Time
	RevokedAt pgtype.Timestamptz
	UserAgent *string
	Ip        *netip.Addr
	CreatedAt time.Time
}

type Tag struct {
	ID          uuid.UUID
	Name        string
	Description *string
	ColorKey    *string
	PostCount   int32
	CreatedAt   time.Time
}

type User struct {
	ID             uuid.UUID
	Username       string
	Email          *string
	DisplayName    string
	AvatarUrl      *string
	Bio            *string
	WebsiteUrl     *string
	GithubUsername *string
	Location       *string
	Role           string
	IsSuspended    bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
