// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addViewCounts = `-- name: AddViewCounts :exec
UPDATE posts SET view_count = view_count + d.delta
FROM (SELECT unnest($1::uuid[]) AS id, unnest($2::bigint[]) AS delta) d
WHERE posts.id = d.id
`

type AddViewCountsParams struct {
	Ids    []uuid.UUID
	Deltas []int64
}

// Apply many buffered view deltas in one statement. Rows for posts that no
// longer exist simply match nothing.
func (q *Queries) AddViewCounts(ctx context.Context, arg AddViewCountsParams) error {
	_, err := q.db.Exec(ctx, addViewCounts, arg.Ids, arg.Deltas)
	return err
}

const createPostTx = `-- name: CreatePostTx :one
INSERT INTO posts (
    id, author_id, slug, title, subtitle, body_markdown, body_html,
    cover_image_url, status, reading_minutes, canonical_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, 'draft', $9, $10
)
RETURNING id, author_id, slug, title, subtitle, body_markdown, body_html, cover_image_url, status, reading_minutes, canonical_url, comment_count, reaction_count, view_count, published_at, created_at, updated_at, deleted_at, search_vector
`

type CreatePostTxParams struct {
	ID             uuid.UUID
	AuthorID       uuid.UUID
	Slug           string
	Title          string
	Subtitle       *string
	BodyMarkdown   string
	BodyHtml       string
	CoverImageUrl  *string
	ReadingMinutes int32
	CanonicalUrl   *string
}

func (q *Queries) CreatePostTx(ctx context.Context, arg CreatePostTxParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPostTx,
		arg.ID,
		arg.AuthorID,
		arg.Slug,
		arg.Title,
		arg.Subtitle,
		arg.BodyMarkdown,
		arg.BodyHtml,
		arg.CoverImageUrl,
		arg.ReadingMinutes,
		arg.CanonicalUrl,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.BodyMarkdown,
		&i.BodyHtml,
		&i.CoverImageUrl,
		&i.Status,
		&i.ReadingMinutes,
		&i.CanonicalUrl,
		&i.CommentCount,
		&i.ReactionCount,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, author_id, slug, title, subtitle, body_markdown, body_html, cover_image_url, status, reading_minutes, canonical_url, comment_count, reaction_count, view_count, published_at, created_at, updated_at, deleted_at, search_vector FROM posts WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPostByID(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.BodyMarkdown,
		&i.BodyHtml,
		&i.CoverImageUrl,
		&i.Status,
		&i.ReadingMinutes,
		&i.CanonicalUrl,
		&i.CommentCount,
		&i.ReactionCount,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}

const getPublishedPostBySlug = `-- name: GetPublishedPostBySlug :one
SELECT p.id, p.author_id, p.slug, p.title, p.subtitle, p.body_markdown, p.body_html, p.cover_image_url, p.status, p.reading_minutes, p.canonical_url, p.comment_count, p.reaction_count, p.view_count, p.published_at, p.created_at, p.updated_at, p.deleted_at, p.search_vector FROM posts p
JOIN users u ON u.id = p.author_id
WHERE u.username = $1 AND p.slug = $2
  AND p.status = 'published' AND p.deleted_at IS NULL
`

type GetPublishedPostBySlugParams struct {
	Username string
	Slug     string
}

func (q *Queries) GetPublishedPostBySlug(ctx context.Context, arg GetPublishedPostBySlugParams) (Post, error) {
	row := q.db.QueryRow(ctx, getPublishedPostBySlug, arg.Username, arg.Slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.BodyMarkdown,
		&i.BodyHtml,
		&i.CoverImageUrl,
		&i.Status,
		&i.ReadingMinutes,
		&i.CanonicalUrl,
		&i.CommentCount,
		&i.ReactionCount,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}

const listFeedByTag = `-- name: ListFeedByTag :many
SELECT p.id, p.author_id, p.slug, p.title, p.subtitle, p.body_markdown, p.body_html, p.cover_image_url, p.status, p.reading_minutes, p.canonical_url, p.comment_count, p.reaction_count, p.view_count, p.published_at, p.created_at, p.updated_at, p.deleted_at, p.search_vector FROM posts p
JOIN post_tags pt ON pt.post_id = p.id
JOIN tags t ON t.id = pt.tag_id
WHERE t.name = $1 AND p.status = 'published' AND p.deleted_at IS NULL
  AND ($2::bool = false OR (p.published_at, p.id) < ($3::timestamptz, $4::uuid))
ORDER BY p.published_at DESC, p.id DESC
LIMIT $5
`

type ListFeedByTagParams struct {
	Tag       string
	UseCursor bool
	CursorAt  time.Time
	CursorID  uuid.UUID
	Lim       int32
}

type ListFeedByTagRow struct {
	Post Post
}

func (q *Queries) ListFeedByTag(ctx context.Context, arg ListFeedByTagParams) ([]ListFeedByTagRow, error) {
	rows, err := q.db.Query(ctx, listFeedByTag,
		arg.Tag,
		arg.UseCursor,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedByTagRow
	for rows.Next() {
		var i ListFeedByTagRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.AuthorID,
			&i.Post.Slug,
			&i.Post.Title,
			&i.Post.Subtitle,
			&i.Post.BodyMarkdown,
			&i.Post.BodyHtml,
			&i.Post.CoverImageUrl,
			&i.Post.Status,
			&i.Post.ReadingMinutes,
			&i.Post.CanonicalUrl,
			&i.Post.CommentCount,
			&i.Post.ReactionCount,
			&i.Post.ViewCount,
			&i.Post.PublishedAt,
			&i.Post.CreatedAt,
			&i.Post.UpdatedAt,
			&i.Post.DeletedAt,
			&i.Post.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHotFeed = `-- name: ListHotFeed :many
SELECT p.id, p.author_id, p.slug, p.title, p.subtitle, p.body_markdown, p.body_html, p.cover_image_url, p.status, p.reading_minutes, p.canonical_url, p.comment_count, p.reaction_count, p.view_count, p.published_at, p.created_at, p.updated_at, p.deleted_at, p.search_vector FROM posts p
WHERE p.status = 'published' AND p.deleted_at IS NULL
  AND p.published_at > now() - INTERVAL '7 days'
ORDER BY (p.reaction_count + 2 * p.comment_count + 1)
    / POWER(EXTRACT(EPOCH FROM (now() - p.published_at)) / 3600 + 2, 1.5) DESC
LIMIT $1
`

type ListHotFeedRow struct {
	Post Post
}

// Hacker News style ranking (docs/02-data-model.md §8): comments weigh 2x
// reactions, and the age penalty pushes older posts down. Bounded to 7 days so
// the scan stays small; the result is cached in Redis, so this runs rarely.
// The score is only an ORDER BY key, never selected, to avoid a float-to-int
// scan mismatch.
func (q *Queries) ListHotFeed(ctx context.Context, lim int32) ([]ListHotFeedRow, error) {
	rows, err := q.db.Query(ctx, listHotFeed, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHotFeedRow
	for rows.Next() {
		var i ListHotFeedRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.AuthorID,
			&i.Post.Slug,
			&i.Post.Title,
			&i.Post.Subtitle,
			&i.Post.BodyMarkdown,
			&i.Post.BodyHtml,
			&i.Post.CoverImageUrl,
			&i.Post.Status,
			&i.Post.ReadingMinutes,
			&i.Post.CanonicalUrl,
			&i.Post.CommentCount,
			&i.Post.ReactionCount,
			&i.Post.ViewCount,
			&i.Post.PublishedAt,
			&i.Post.CreatedAt,
			&i.Post.UpdatedAt,
			&i.Post.DeletedAt,
			&i.Post.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyPosts = `-- name: ListMyPosts :many
SELECT id, author_id, slug, title, subtitle, body_markdown, body_html, cover_image_url, status, reading_minutes, canonical_url, comment_count, reaction_count, view_count, published_at, created_at, updated_at, deleted_at, search_vector FROM posts
WHERE author_id = $1 AND deleted_at IS NULL
  AND ($2::text = 'all' OR status = $2::text)
ORDER BY updated_at DESC
LIMIT $3
`

type ListMyPostsParams struct {
	AuthorID     uuid.UUID
	StatusFilter string
	Lim          int32
}

func (q *Queries) ListMyPosts(ctx context.Context, arg ListMyPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listMyPosts, arg.AuthorID, arg.StatusFilter, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Slug,
			&i.Title,
			&i.Subtitle,
			&i.BodyMarkdown,
			&i.BodyHtml,
			&i.CoverImageUrl,
			&i.Status,
			&i.ReadingMinutes,
			&i.CanonicalUrl,
			&i.CommentCount,
			&i.ReactionCount,
			&i.ViewCount,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedFeed = `-- name: ListPublishedFeed :many
SELECT id, author_id, slug, title, subtitle, body_markdown, body_html, cover_image_url, status, reading_minutes, canonical_url, comment_count, reaction_count, view_count, published_at, created_at, updated_at, deleted_at, search_vector FROM posts
WHERE status = 'published' AND deleted_at IS NULL
  AND ($1::bool = false OR (published_at, id) < ($2::timestamptz, $3::uuid))
ORDER BY published_at DESC, id DESC
LIMIT $4
`

type ListPublishedFeedParams struct {
	UseCursor bool
	CursorAt  time.Time
	CursorID  uuid.UUID
	Lim       int32
}

// Cursor pagination matching idx_posts_feed. The tuple comparison walks the
// index directly; offset pagination is forbidden (docs/03-api.md §1).
func (q *Queries) ListPublishedFeed(ctx context.Context, arg ListPublishedFeedParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPublishedFeed,
		arg.UseCursor,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Slug,
			&i.Title,
			&i.Subtitle,
			&i.BodyMarkdown,
			&i.BodyHtml,
			&i.CoverImageUrl,
			&i.Status,
			&i.ReadingMinutes,
			&i.CanonicalUrl,
			&i.CommentCount,
			&i.ReactionCount,
			&i.ViewCount,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishPost = `-- name: PublishPost :one
UPDATE posts SET status = 'published', slug = $1, published_at = now(), updated_at = now()
WHERE id = $2 AND author_id = $3 AND deleted_at IS NULL
RETURNING id, author_id, slug, title, subtitle, body_markdown, body_html, cover_image_url, status, reading_minutes, canonical_url, comment_count, reaction_count, view_count, published_at, created_at, updated_at, deleted_at, search_vector
`

type PublishPostParams struct {
	Slug     string
	ID       uuid.UUID
	AuthorID uuid.UUID
}

func (q *Queries) PublishPost(ctx context.Context, arg PublishPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, publishPost, arg.Slug, arg.ID, arg.AuthorID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.BodyMarkdown,
		&i.BodyHtml,
		&i.CoverImageUrl,
		&i.Status,
		&i.ReadingMinutes,
		&i.CanonicalUrl,
		&i.CommentCount,
		&i.ReactionCount,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}

const searchPosts = `-- name: SearchPosts :many
SELECT p.id, p.author_id, p.slug, p.title, p.subtitle, p.body_markdown, p.body_html, p.cover_image_url, p.status, p.reading_minutes, p.canonical_url, p.comment_count, p.reaction_count, p.view_count, p.published_at, p.created_at, p.updated_at, p.deleted_at, p.search_vector,
    ts_headline('simple', p.body_markdown, query, 'MaxWords=30, MinWords=15, MaxFragments=1') AS headline
FROM posts p, websearch_to_tsquery('simple', $1) query
WHERE p.status = 'published' AND p.deleted_at IS NULL
  AND p.search_vector @@ query
ORDER BY ts_rank(p.search_vector, query) DESC
LIMIT $2
`

type SearchPostsParams struct {
	Q   string
	Lim int32
}

type SearchPostsRow struct {
	Post     Post
	Headline []byte
}

// Full-text search over the generated search_vector. 'simple' config matches
// how the vector is built (no English stemmer to mangle Vietnamese). The
// headline is a snippet of the body with the matched terms marked.
func (q *Queries) SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error) {
	rows, err := q.db.Query(ctx, searchPosts, arg.Q, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsRow
	for rows.Next() {
		var i SearchPostsRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.AuthorID,
			&i.Post.Slug,
			&i.Post.Title,
			&i.Post.Subtitle,
			&i.Post.BodyMarkdown,
			&i.Post.BodyHtml,
			&i.Post.CoverImageUrl,
			&i.Post.Status,
			&i.Post.ReadingMinutes,
			&i.Post.CanonicalUrl,
			&i.Post.CommentCount,
			&i.Post.ReactionCount,
			&i.Post.ViewCount,
			&i.Post.PublishedAt,
			&i.Post.CreatedAt,
			&i.Post.UpdatedAt,
			&i.Post.DeletedAt,
			&i.Post.SearchVector,
			&i.Headline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const slugExistsForAuthor = `-- name: SlugExistsForAuthor :one
SELECT EXISTS (
    SELECT 1 FROM posts
    WHERE author_id = $1 AND slug = $2 AND deleted_at IS NULL
)
`

type SlugExistsForAuthorParams struct {
	AuthorID uuid.UUID
	Slug     string
}

func (q *Queries) SlugExistsForAuthor(ctx context.Context, arg SlugExistsForAuthorParams) (bool, error) {
	row := q.db.QueryRow(ctx, slugExistsForAuthor, arg.AuthorID, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeletePost = `-- name: SoftDeletePost :exec
UPDATE posts SET deleted_at = now()
WHERE id = $1 AND author_id = $2 AND deleted_at IS NULL
`

type SoftDeletePostParams struct {
	ID       uuid.UUID
	AuthorID uuid.UUID
}

func (q *Queries) SoftDeletePost(ctx context.Context, arg SoftDeletePostParams) error {
	_, err := q.db.Exec(ctx, softDeletePost, arg.ID, arg.AuthorID)
	return err
}

const unpublishPost = `-- name: UnpublishPost :one
UPDATE posts SET status = 'draft', updated_at = now()
WHERE id = $1 AND author_id = $2 AND deleted_at IS NULL
RETURNING id, author_id, slug, title, subtitle, body_markdown, body_html, cover_image_url, status, reading_minutes, canonical_url, comment_count, reaction_count, view_count, published_at, created_at, updated_at, deleted_at, search_vector
`

type UnpublishPostParams struct {
	ID       uuid.UUID
	AuthorID uuid.UUID
}

func (q *Queries) UnpublishPost(ctx context.Context, arg UnpublishPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, unpublishPost, arg.ID, arg.AuthorID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.BodyMarkdown,
		&i.BodyHtml,
		&i.CoverImageUrl,
		&i.Status,
		&i.ReadingMinutes,
		&i.CanonicalUrl,
		&i.CommentCount,
		&i.ReactionCount,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts SET
    title           = COALESCE($1, title),
    subtitle        = COALESCE($2, subtitle),
    body_markdown   = COALESCE($3, body_markdown),
    body_html       = COALESCE($4, body_html),
    cover_image_url = COALESCE($5, cover_image_url),
    reading_minutes = COALESCE($6, reading_minutes),
    updated_at      = now()
WHERE id = $7 AND author_id = $8 AND deleted_at IS NULL
RETURNING id, author_id, slug, title, subtitle, body_markdown, body_html, cover_image_url, status, reading_minutes, canonical_url, comment_count, reaction_count, view_count, published_at, created_at, updated_at, deleted_at, search_vector
`

type UpdatePostParams struct {
	Title          *string
	Subtitle       *string
	BodyMarkdown   *string
	BodyHtml       *string
	CoverImageUrl  *string
	ReadingMinutes *int32
	ID             uuid.UUID
	AuthorID       uuid.UUID
}

// COALESCE keeps every unset field: a PATCH that changes only the title leaves
// the body untouched. Only the author can update, enforced in the WHERE clause.
func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.Title,
		arg.Subtitle,
		arg.BodyMarkdown,
		arg.BodyHtml,
		arg.CoverImageUrl,
		arg.ReadingMinutes,
		arg.ID,
		arg.AuthorID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.BodyMarkdown,
		&i.BodyHtml,
		&i.CoverImageUrl,
		&i.Status,
		&i.ReadingMinutes,
		&i.CanonicalUrl,
		&i.CommentCount,
		&i.ReactionCount,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}
