// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPostTx = `-- name: CreatePostTx :one
INSERT INTO posts (
    id, author_id, slug, title, subtitle, body_markdown, body_html,
    cover_image_url, status, reading_minutes, canonical_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, 'draft', $9, $10
)
RETURNING id, author_id, slug, title, subtitle, body_markdown, body_html, cover_image_url, status, reading_minutes, canonical_url, comment_count, reaction_count, view_count, published_at, created_at, updated_at, deleted_at, search_vector
`

type CreatePostTxParams struct {
	ID             uuid.UUID
	AuthorID       uuid.UUID
	Slug           string
	Title          string
	Subtitle       *string
	BodyMarkdown   string
	BodyHtml       string
	CoverImageUrl  *string
	ReadingMinutes int32
	CanonicalUrl   *string
}

func (q *Queries) CreatePostTx(ctx context.Context, arg CreatePostTxParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPostTx,
		arg.ID,
		arg.AuthorID,
		arg.Slug,
		arg.Title,
		arg.Subtitle,
		arg.BodyMarkdown,
		arg.BodyHtml,
		arg.CoverImageUrl,
		arg.ReadingMinutes,
		arg.CanonicalUrl,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.BodyMarkdown,
		&i.BodyHtml,
		&i.CoverImageUrl,
		&i.Status,
		&i.ReadingMinutes,
		&i.CanonicalUrl,
		&i.CommentCount,
		&i.ReactionCount,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, author_id, slug, title, subtitle, body_markdown, body_html, cover_image_url, status, reading_minutes, canonical_url, comment_count, reaction_count, view_count, published_at, created_at, updated_at, deleted_at, search_vector FROM posts WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPostByID(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.BodyMarkdown,
		&i.BodyHtml,
		&i.CoverImageUrl,
		&i.Status,
		&i.ReadingMinutes,
		&i.CanonicalUrl,
		&i.CommentCount,
		&i.ReactionCount,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}

const getPublishedPostBySlug = `-- name: GetPublishedPostBySlug :one
SELECT p.id, p.author_id, p.slug, p.title, p.subtitle, p.body_markdown, p.body_html, p.cover_image_url, p.status, p.reading_minutes, p.canonical_url, p.comment_count, p.reaction_count, p.view_count, p.published_at, p.created_at, p.updated_at, p.deleted_at, p.search_vector FROM posts p
JOIN users u ON u.id = p.author_id
WHERE u.username = $1 AND p.slug = $2
  AND p.status = 'published' AND p.deleted_at IS NULL
`

type GetPublishedPostBySlugParams struct {
	Username string
	Slug     string
}

func (q *Queries) GetPublishedPostBySlug(ctx context.Context, arg GetPublishedPostBySlugParams) (Post, error) {
	row := q.db.QueryRow(ctx, getPublishedPostBySlug, arg.Username, arg.Slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.BodyMarkdown,
		&i.BodyHtml,
		&i.CoverImageUrl,
		&i.Status,
		&i.ReadingMinutes,
		&i.CanonicalUrl,
		&i.CommentCount,
		&i.ReactionCount,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}

const listMyPosts = `-- name: ListMyPosts :many
SELECT id, author_id, slug, title, subtitle, body_markdown, body_html, cover_image_url, status, reading_minutes, canonical_url, comment_count, reaction_count, view_count, published_at, created_at, updated_at, deleted_at, search_vector FROM posts
WHERE author_id = $1 AND deleted_at IS NULL
  AND ($2::text = 'all' OR status = $2::text)
ORDER BY updated_at DESC
LIMIT $3
`

type ListMyPostsParams struct {
	AuthorID     uuid.UUID
	StatusFilter string
	Lim          int32
}

func (q *Queries) ListMyPosts(ctx context.Context, arg ListMyPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listMyPosts, arg.AuthorID, arg.StatusFilter, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Slug,
			&i.Title,
			&i.Subtitle,
			&i.BodyMarkdown,
			&i.BodyHtml,
			&i.CoverImageUrl,
			&i.Status,
			&i.ReadingMinutes,
			&i.CanonicalUrl,
			&i.CommentCount,
			&i.ReactionCount,
			&i.ViewCount,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedFeed = `-- name: ListPublishedFeed :many
SELECT id, author_id, slug, title, subtitle, body_markdown, body_html, cover_image_url, status, reading_minutes, canonical_url, comment_count, reaction_count, view_count, published_at, created_at, updated_at, deleted_at, search_vector FROM posts
WHERE status = 'published' AND deleted_at IS NULL
  AND ($1::bool = false OR (published_at, id) < ($2::timestamptz, $3::uuid))
ORDER BY published_at DESC, id DESC
LIMIT $4
`

type ListPublishedFeedParams struct {
	UseCursor bool
	CursorAt  time.Time
	CursorID  uuid.UUID
	Lim       int32
}

// Cursor pagination matching idx_posts_feed. The tuple comparison walks the
// index directly; offset pagination is forbidden (docs/03-api.md §1).
func (q *Queries) ListPublishedFeed(ctx context.Context, arg ListPublishedFeedParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPublishedFeed,
		arg.UseCursor,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Slug,
			&i.Title,
			&i.Subtitle,
			&i.BodyMarkdown,
			&i.BodyHtml,
			&i.CoverImageUrl,
			&i.Status,
			&i.ReadingMinutes,
			&i.CanonicalUrl,
			&i.CommentCount,
			&i.ReactionCount,
			&i.ViewCount,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishPost = `-- name: PublishPost :one
UPDATE posts SET status = 'published', slug = $1, published_at = now(), updated_at = now()
WHERE id = $2 AND author_id = $3 AND deleted_at IS NULL
RETURNING id, author_id, slug, title, subtitle, body_markdown, body_html, cover_image_url, status, reading_minutes, canonical_url, comment_count, reaction_count, view_count, published_at, created_at, updated_at, deleted_at, search_vector
`

type PublishPostParams struct {
	Slug     string
	ID       uuid.UUID
	AuthorID uuid.UUID
}

func (q *Queries) PublishPost(ctx context.Context, arg PublishPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, publishPost, arg.Slug, arg.ID, arg.AuthorID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.BodyMarkdown,
		&i.BodyHtml,
		&i.CoverImageUrl,
		&i.Status,
		&i.ReadingMinutes,
		&i.CanonicalUrl,
		&i.CommentCount,
		&i.ReactionCount,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}

const slugExistsForAuthor = `-- name: SlugExistsForAuthor :one
SELECT EXISTS (
    SELECT 1 FROM posts
    WHERE author_id = $1 AND slug = $2 AND deleted_at IS NULL
)
`

type SlugExistsForAuthorParams struct {
	AuthorID uuid.UUID
	Slug     string
}

func (q *Queries) SlugExistsForAuthor(ctx context.Context, arg SlugExistsForAuthorParams) (bool, error) {
	row := q.db.QueryRow(ctx, slugExistsForAuthor, arg.AuthorID, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeletePost = `-- name: SoftDeletePost :exec
UPDATE posts SET deleted_at = now()
WHERE id = $1 AND author_id = $2 AND deleted_at IS NULL
`

type SoftDeletePostParams struct {
	ID       uuid.UUID
	AuthorID uuid.UUID
}

func (q *Queries) SoftDeletePost(ctx context.Context, arg SoftDeletePostParams) error {
	_, err := q.db.Exec(ctx, softDeletePost, arg.ID, arg.AuthorID)
	return err
}

const unpublishPost = `-- name: UnpublishPost :one
UPDATE posts SET status = 'draft', updated_at = now()
WHERE id = $1 AND author_id = $2 AND deleted_at IS NULL
RETURNING id, author_id, slug, title, subtitle, body_markdown, body_html, cover_image_url, status, reading_minutes, canonical_url, comment_count, reaction_count, view_count, published_at, created_at, updated_at, deleted_at, search_vector
`

type UnpublishPostParams struct {
	ID       uuid.UUID
	AuthorID uuid.UUID
}

func (q *Queries) UnpublishPost(ctx context.Context, arg UnpublishPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, unpublishPost, arg.ID, arg.AuthorID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.BodyMarkdown,
		&i.BodyHtml,
		&i.CoverImageUrl,
		&i.Status,
		&i.ReadingMinutes,
		&i.CanonicalUrl,
		&i.CommentCount,
		&i.ReactionCount,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts SET
    title           = COALESCE($1, title),
    subtitle        = COALESCE($2, subtitle),
    body_markdown   = COALESCE($3, body_markdown),
    body_html       = COALESCE($4, body_html),
    cover_image_url = COALESCE($5, cover_image_url),
    reading_minutes = COALESCE($6, reading_minutes),
    updated_at      = now()
WHERE id = $7 AND author_id = $8 AND deleted_at IS NULL
RETURNING id, author_id, slug, title, subtitle, body_markdown, body_html, cover_image_url, status, reading_minutes, canonical_url, comment_count, reaction_count, view_count, published_at, created_at, updated_at, deleted_at, search_vector
`

type UpdatePostParams struct {
	Title          *string
	Subtitle       *string
	BodyMarkdown   *string
	BodyHtml       *string
	CoverImageUrl  *string
	ReadingMinutes *int32
	ID             uuid.UUID
	AuthorID       uuid.UUID
}

// COALESCE keeps every unset field: a PATCH that changes only the title leaves
// the body untouched. Only the author can update, enforced in the WHERE clause.
func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.Title,
		arg.Subtitle,
		arg.BodyMarkdown,
		arg.BodyHtml,
		arg.CoverImageUrl,
		arg.ReadingMinutes,
		arg.ID,
		arg.AuthorID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.BodyMarkdown,
		&i.BodyHtml,
		&i.CoverImageUrl,
		&i.Status,
		&i.ReadingMinutes,
		&i.CanonicalUrl,
		&i.CommentCount,
		&i.ReactionCount,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
	)
	return i, err
}
