// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reaction.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const addBookmark = `-- name: AddBookmark :exec
INSERT INTO bookmarks (user_id, post_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddBookmarkParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) AddBookmark(ctx context.Context, arg AddBookmarkParams) error {
	_, err := q.db.Exec(ctx, addBookmark, arg.UserID, arg.PostID)
	return err
}

const addReactionTx = `-- name: AddReactionTx :execrows
INSERT INTO reactions (user_id, post_id, kind)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddReactionTxParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
	Kind   string
}

// Idempotent: a repeated reaction of the same kind changes nothing. The rows
// affected tells the service whether to bump the post's reaction count.
func (q *Queries) AddReactionTx(ctx context.Context, arg AddReactionTxParams) (int64, error) {
	result, err := q.db.Exec(ctx, addReactionTx, arg.UserID, arg.PostID, arg.Kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adjustPostReactionCount = `-- name: AdjustPostReactionCount :exec
UPDATE posts SET reaction_count = reaction_count + $1 WHERE id = $2
`

type AdjustPostReactionCountParams struct {
	Delta  int32
	PostID uuid.UUID
}

func (q *Queries) AdjustPostReactionCount(ctx context.Context, arg AdjustPostReactionCountParams) error {
	_, err := q.db.Exec(ctx, adjustPostReactionCount, arg.Delta, arg.PostID)
	return err
}

const getPostReactionCount = `-- name: GetPostReactionCount :one
SELECT reaction_count FROM posts WHERE id = $1
`

// The reaction module maintains this denormalized counter, so it also reads it
// back to return the fresh total after a toggle.
func (q *Queries) GetPostReactionCount(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getPostReactionCount, id)
	var reaction_count int32
	err := row.Scan(&reaction_count)
	return reaction_count, err
}

const listBookmarkedPostIDs = `-- name: ListBookmarkedPostIDs :many
SELECT p.id FROM posts p
JOIN bookmarks b ON b.post_id = p.id
WHERE b.user_id = $1 AND p.deleted_at IS NULL
ORDER BY b.created_at DESC
LIMIT $2
`

type ListBookmarkedPostIDsParams struct {
	UserID uuid.UUID
	Lim    int32
}

// Ids of the user's saved posts, most-recently saved first. The post module
// loads and enriches them, reusing its card logic. Bounded by limit; a per-user
// bookmark list is small enough that a single page suffices for now.
func (q *Queries) ListBookmarkedPostIDs(ctx context.Context, arg ListBookmarkedPostIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listBookmarkedPostIDs, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBookmark = `-- name: RemoveBookmark :exec
DELETE FROM bookmarks WHERE user_id = $1 AND post_id = $2
`

type RemoveBookmarkParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) RemoveBookmark(ctx context.Context, arg RemoveBookmarkParams) error {
	_, err := q.db.Exec(ctx, removeBookmark, arg.UserID, arg.PostID)
	return err
}

const removeReactionTx = `-- name: RemoveReactionTx :execrows
DELETE FROM reactions
WHERE user_id = $1 AND post_id = $2 AND kind = $3
`

type RemoveReactionTxParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
	Kind   string
}

func (q *Queries) RemoveReactionTx(ctx context.Context, arg RemoveReactionTxParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeReactionTx, arg.UserID, arg.PostID, arg.Kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const viewerBookmarked = `-- name: ViewerBookmarked :one
SELECT EXISTS (SELECT 1 FROM bookmarks WHERE user_id = $1 AND post_id = $2)
`

type ViewerBookmarkedParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) ViewerBookmarked(ctx context.Context, arg ViewerBookmarkedParams) (bool, error) {
	row := q.db.QueryRow(ctx, viewerBookmarked, arg.UserID, arg.PostID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const viewerReactions = `-- name: ViewerReactions :many
SELECT kind FROM reactions WHERE user_id = $1 AND post_id = $2
`

type ViewerReactionsParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) ViewerReactions(ctx context.Context, arg ViewerReactionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, viewerReactions, arg.UserID, arg.PostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var kind string
		if err := rows.Scan(&kind); err != nil {
			return nil, err
		}
		items = append(items, kind)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
