// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tag.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const attachTagTx = `-- name: AttachTagTx :exec
INSERT INTO post_tags (post_id, tag_id, position)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AttachTagTxParams struct {
	PostID   uuid.UUID
	TagID    uuid.UUID
	Position int16
}

func (q *Queries) AttachTagTx(ctx context.Context, arg AttachTagTxParams) error {
	_, err := q.db.Exec(ctx, attachTagTx, arg.PostID, arg.TagID, arg.Position)
	return err
}

const incrementTagCounts = `-- name: IncrementTagCounts :exec
UPDATE tags SET post_count = post_count + 1 WHERE id = ANY($1::uuid[])
`

func (q *Queries) IncrementTagCounts(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementTagCounts, ids)
	return err
}

const popularTags = `-- name: PopularTags :many
SELECT id, name, description, color_key, post_count, created_at FROM tags ORDER BY post_count DESC LIMIT $1
`

func (q *Queries) PopularTags(ctx context.Context, lim int32) ([]Tag, error) {
	rows, err := q.db.Query(ctx, popularTags, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ColorKey,
			&i.PostCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTags = `-- name: SearchTags :many
SELECT id, name, description, color_key, post_count, created_at FROM tags
WHERE name ILIKE $1 || '%'
ORDER BY post_count DESC
LIMIT $2
`

type SearchTagsParams struct {
	Query *string
	Lim   int32
}

// Prefix/fuzzy autocomplete over tag names, most-used first.
func (q *Queries) SearchTags(ctx context.Context, arg SearchTagsParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, searchTags, arg.Query, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ColorKey,
			&i.PostCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tagsForPost = `-- name: TagsForPost :many
SELECT t.id, t.name, t.description, t.color_key, t.post_count, t.created_at FROM tags t
JOIN post_tags pt ON pt.tag_id = t.id
WHERE pt.post_id = $1
ORDER BY pt.position
`

func (q *Queries) TagsForPost(ctx context.Context, postID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, tagsForPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ColorKey,
			&i.PostCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tagsForPosts = `-- name: TagsForPosts :many
SELECT pt.post_id, t.id, t.name, t.color_key
FROM tags t
JOIN post_tags pt ON pt.tag_id = t.id
WHERE pt.post_id = ANY($1::uuid[])
ORDER BY pt.position
`

type TagsForPostsRow struct {
	PostID   uuid.UUID
	ID       uuid.UUID
	Name     string
	ColorKey *string
}

// Batch variant of TagsForPost so a feed resolves tags for every post at once.
func (q *Queries) TagsForPosts(ctx context.Context, postIds []uuid.UUID) ([]TagsForPostsRow, error) {
	rows, err := q.db.Query(ctx, tagsForPosts, postIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TagsForPostsRow
	for rows.Next() {
		var i TagsForPostsRow
		if err := rows.Scan(
			&i.PostID,
			&i.ID,
			&i.Name,
			&i.ColorKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (id, name)
VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, description, color_key, post_count, created_at
`

type UpsertTagParams struct {
	ID   uuid.UUID
	Name string
}

// Create the tag or return the existing one. ON CONFLICT DO UPDATE (rather than
// DO NOTHING) so RETURNING always yields a row even when the tag already exists.
func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, upsertTag, arg.ID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ColorKey,
		&i.PostCount,
		&i.CreatedAt,
	)
	return i, err
}
