// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, email, display_name, avatar_url, github_username)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, email, display_name, avatar_url, bio, website_url, github_username, location, role, is_suspended, created_at, updated_at
`

type CreateUserParams struct {
	ID             uuid.UUID
	Username       string
	Email          *string
	DisplayName    string
	AvatarUrl      *string
	GithubUsername *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.GithubUsername,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.WebsiteUrl,
		&i.GithubUsername,
		&i.Location,
		&i.Role,
		&i.IsSuspended,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, display_name, avatar_url, bio, website_url, github_username, location, role, is_suspended, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.WebsiteUrl,
		&i.GithubUsername,
		&i.Location,
		&i.Role,
		&i.IsSuspended,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, display_name, avatar_url, bio, website_url, github_username, location, role, is_suspended, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.WebsiteUrl,
		&i.GithubUsername,
		&i.Location,
		&i.Role,
		&i.IsSuspended,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, username, display_name, avatar_url
FROM users WHERE id = ANY($1::uuid[])
`

type GetUsersByIDsRow struct {
	ID          uuid.UUID
	Username    string
	DisplayName string
	AvatarUrl   *string
}

// Batch lookup so a feed of many posts resolves every author in one query
// instead of one per post.
func (q *Queries) GetUsersByIDs(ctx context.Context, ids []uuid.UUID) ([]GetUsersByIDsRow, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByIDsRow
	for rows.Next() {
		var i GetUsersByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS (SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) UsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
